I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 73, in script
    with moveincenter
  File "game/script.rpy", line 73, in <module>
    with moveincenter
NameError: name 'moveincenter' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 73, in script
    with moveincenter
  File "/Users/luis.sanchez/Downloads/games/renpy-8.3.2-sdk/renpy/ast.py", line 1354, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Users/luis.sanchez/Downloads/games/renpy-8.3.2-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/luis.sanchez/Downloads/games/renpy-8.3.2-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 73, in <module>
    with moveincenter
NameError: name 'moveincenter' is not defined

macOS-15.0-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
init demo 1.0
Thu Oct 10 12:25:03 2024
